# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeosquareGrid
                                 A QGIS plugin
 Geosquare Grid
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-17
        copyright            : (C) 2025 by PT Geo Inovasi Nusantara
        email                : admin@geosquare.ai
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.utils import plugins

if 'processing' not in plugins:
        import processing

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeosquareGrid class from file GeosquareGrid.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geosquare_grid import GeosquareGrid
    return GeosquareGrid(iface)
